### ISSUE TITLE
Getting last modified time from s3_iter_bucket

### ISSUE THREAD

**Issue by salilb** [piskvorky/smart_open#21]
Is it possible to get the last_modified time of the file when using the s3_iter_bucket function? 
If not, would you consider adding a flag so that the modified time is returned as part of the tuple?
Thanks

**Comment by piskvorky** [comment]
Hmm... if we do add that, we should add it in a more general way. So that next time someone doesn't come and ask for another flag, for another metadata X.

Do you have an idea of how to do it cleanly?

**Comment by salilb** [comment]
Why not return the key as is instead of just the key name? That way the user can extract the name, size and last_modified time.

**Comment by piskvorky** [comment]
Sounds reasonable. It's a backward incompatible change though, so we have to communicate it clearly.

Can you start a PR?

**Comment by salilb** [comment]
I sent a PR.

**Comment by piskvorky** [comment]
Thanks, I'll check it out!
