### ISSUE TITLE
Support of WebHDFS

### ISSUE THREAD

**Issue by ziky90** [piskvorky/smart_open#23]
My idea is to add possibility to read from WebHDFS. 
It would probably need to be implemented as some wrapper on top of WebHDFS API. 
https://hadoop.apache.org/docs/r1.0.4/webhdfs.html

Based on the observations from API:
- Streaming seems to be possible
- It will involve probably requests library dependency (is this possible?)
- It might involve necessity of creating some config file with details about login to WebHDFS

Would this addition be appreciated in smart_open? I can try to work on PR, hopefully in the near future.

**Comment by piskvorky** [comment]
Yes, we accept any new functionality that fits the mission of `smart_open` = Pythonic API read/write access to large (streamed) data files, no matter the protocol.

Requests is a stable library, depending on it is no problem.

Authentication / login configs: as long as it doesn't affect the other (existing) code paths and is conceptually sane (maintainable).

**Comment by ziky90** [comment]
Implemented in #29 #31
