### ISSUE TITLE
Bug (maybe feature) in HdfsOpenRead

### ISSUE THREAD

**Issue by ziky90** [piskvorky/smart_open#24]
On line 249 I have noticed a minor bug in reading from HDFS

There is used command `hadoop fs -cat` which based on the documentation http://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-common/FileSystemShell.html reads any file mounted to Hadoop (HDFS, FS, HFTP FS, S3 FS, and others)

Correctly to meet what smart_open claims to do there should be used `hdfs dfs -cat`.
http://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-hdfs/HDFSCommands.html#dfs

I can do a PR with fix if this is really a bug.

If this is expected behaviour then I would change the documentation + I would not limit files schema to only HDFS.

**Comment by piskvorky** [comment]
I don't think anybody ever used that code path, and there are no unit tests for it.

So whatever works for you -- the HDFS support is extremely rudimentary now.
