### ISSUE TITLE
missing readline in S3OpenRead

### ISSUE THREAD

**Issue by ziky90** [piskvorky/smart_open#27]
Missing readline in S3OpenRead is related to and more in detail explained in https://github.com/piskvorky/gensim/issues/421

**Comment by piskvorky** [comment]
Closing as duplicate of #13 .

**Comment by piskvorky** [comment]
@ziky90 can you add this?

**Comment by ziky90** [comment]
@piskvorky Where should I add this?

**Comment by piskvorky** [comment]
In `S3OpenRead`... or what do you mean?

**Comment by ziky90** [comment]
Oh sorry I though that this is a different issue. 
I can try to look up the default behaviour of `readline()` and try to implement it during September.
