### ISSUE TITLE
Cannot install if `LC_ALL=C`

### ISSUE THREAD

**Issue by nikicc** [piskvorky/smart_open#40]
When the system environment variable `LC_ALL=C` I cannot install `smart_open`. The problem is in the dependency `httpretty`, since setup.py requires the version `httpretty==0.8.6` which is [know not to work with](https://github.com/gabrielfalcao/HTTPretty/issues/223) `LC_ALL=C`. The error I get is this:

    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 133: ordinal not in range(128)

`httpretty` fixed this error in version `0.8.8`, so I am wondering if it would be possible to to relax the requirement to `httpretty>=0.8.6`? 

I actually discovered this when trying to install `gensim`, which also did not work since it requires `smart_open`.

**Comment by piskvorky** [comment]
Oh, wow, not good.

A fix will be definitely welcome. Nobody's reported this yet.

**Comment by tmylk** [comment]
Fixed by #41

**Comment by nikicc** [comment]
Can this be reopened, since this does not work in version `1.3.1`?

The problem is that in #41 (that should fix this) the version was set incorrectly to `httpretty>=0.8.8`. It should actually be set to `httpretty>=0.8.12`, since `httpretty` version `0.8.12` is the first version that can be installed with `LC_ALL=C`.

**Comment by piskvorky** [comment]
Yes, if the fix doesn't work, please reopen.

**Comment by nikicc** [comment]
I would, but cannot. Can you?

**Comment by piskvorky** [comment]
Sorry :)

**Comment by piskvorky** [comment]
@tmylk : some progress in https://github.com/gabrielfalcao/HTTPretty/issues/278 .

**Comment by nikicc** [comment]
After a quick check `httpretty 0.8.14` seems to work ok with python3 and `LC_ALL=C` (at least locally). Is there any other reason why we still require httpretty to be fixed? Could we relax the condition to allow `httpretty 0.8.14`?

**Comment by tmylk** [comment]
Thanks for the update. I tried `httpretty 0.8.14` on with Python 3.4 and it failed same way as in https://github.com/piskvorky/smart_open/pull/59 . Raised  https://github.com/gabrielfalcao/HTTPretty/issues/291

**Comment by nikicc** [comment]
OK, I see. I just test the installation part (which seems to be fixed), but forgot to run the tests. Thanks for the effort!

**Comment by tmylk** [comment]
Update: Both httpretty==0.8.12 and httpretty==0.8.14 give test errors.

httpretty==0.8.14 issue reported here
https://github.com/gabrielfalcao/HTTPretty/issues/291

**Comment by nikicc** [comment]
Thanks for the update! I hope this is fixed in the next version of httpretty, so we can update and also fix #40.

**Comment by nikicc** [comment]
I believe this is fixed since `httpretty` was removed from our dependencies by merging #69.

Could we also release a new version to pip?

**Comment by tmylk** [comment]
Before it is released, can you test if the github version works with LC_ALL=C?

**Comment by nikicc** [comment]
I already did and it seem to work OK. If you want to be sure, and re-test it yourself, I did the following:

1. `python setup.py sdist` to build the package.

1. `virtualenv t123` to create empty virtual env and activate it with `. t123/bin/activate`.

1. `LC_ALL=C pip install dist/smart_open-1.3.3.tar.gz`

**Comment by nikicc** [comment]
This has been fixed with #69 and it works in the new release version `1.3.3` 😄
