### ISSUE TITLE
Get rid of file mode restrictions

### ISSUE THREAD

**Issue by piskvorky** [piskvorky/smart_open#49]
Currently `smart_open` is limiting file modes to `('r', 'rb', 'w', 'wb')` [here](https://github.com/piskvorky/smart_open/blob/master/smart_open/smart_open_lib.py#L110).

I don't think there is any reason for this -- remove the restriction and allow whatever mode is supported by the underlying storage ([such as `wb+`](http://stackoverflow.com/questions/34396300/gensim-installation-on-yosemite-using-anaconda)).

**Comment by gojomo** [comment]
This added strictness (from @asieira's 2015-11-05 commit c51f8dcb97f5e5cca70736a81a22f7d9308d7616) is causing problems in gensim's tests (see eg https://github.com/piskvorky/gensim/pull/570), which have used previously-tolerated mode `wb+`.  (Not sure the old code was doing the right thing with `wb+` – there was no case to handle it with regards to S3, for example – but at least it passed it through without error.)

**Comment by piskvorky** [comment]
Yeah this is urgent.

**Comment by tmylk** [comment]
I will have access to a computer and release a fix on 2 Jan
