### ISSUE TITLE
SFTP smart_open does not recover when SSH session is reset.

### ISSUE THREAD

**Issue by matthewlauter** [piskvorky/smart_open#662]
#### Problem description

When using smart_open to read multiple sftp file if the ssh connect is reset smart_open will continue attempting to use closed SSH session. Causing all subsequent calls to fail that used the cached ssh session. 

NOTE: This is caused by some event on the network outside of smart_open.
Error printed when connection is reset: ERROR:paramiko.transport:Socket exception: Connection reset by peer (54). 

Full error log when attempting to use smart_open when SSH connection is reset by peer:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "xxx/python3.9/site-packages/smart_open/smart_open_lib.py", line 235, in open
    binary = _open_binary_stream(uri, binary_mode, transport_params)
  File "xxx/python3.9/site-packages/smart_open/smart_open_lib.py", line 398, in _open_binary_stream
    fobj = submodule.open_uri(uri, mode, transport_params)
  File "xxx/site-packages/smart_open/ssh.py", line 74, in open_uri
    return open(uri_path, mode, transport_params=transport_params, **parsed_uri)
  File "xxx/python3.9/site-packages/smart_open/ssh.py", line 146, in open
    sftp_client = conn.get_transport().open_sftp_client()
  File "xxx/python3.9/site-packages/paramiko/transport.py", line 1097, in open_sftp_client
    return SFTPClient.from_transport(self)
  File "xxx/python3.9/site-packages/paramiko/sftp_client.py", line 164, in from_transport
    chan = t.open_session(
  File "xxx/python3.9/site-packages/paramiko/transport.py", line 875, in open_session
    return self.open_channel(
  File "xxx/python3.9/site-packages/paramiko/transport.py", line 969, in open_channel
    raise SSHException("SSH session not active")
paramiko.ssh_exception.SSHException: SSH session not active

#### Steps/code to reproduce the problem

```
# Values needed to connect to sftp
smart_open_kwargs['transport_params']  = {
            'connect_kwargs': {
                'username': <user>,
                'password': <password>,
                'look_for_keys': False,
                'allow_agent': False,
            },
        }

#Paths to sftp file to open
files = [f"sftp://{sftp_host}/{first_file}", f"sftp://{sftp_host}/{second_file}"]

for file in files:
            # First pass is successful 
            # Second pass fails because smart_open hold on to old 'paramiko.client.SSHClient'
            with smart_open.open(file, **smart_open_kwargs) as file:
                output = file.read()
            
              # Simulate SSH session exiting or erroring.
              list(smart_open.ssh._SSH.values())[0].close()
```

#### Versions

Please provide the output of:

```
Linux-4.15.0-1044-aws-x86_64-with-glibc2.31
Python 3.9.7 (default, Oct 12 2021, 02:43:43) 
[GCC 10.2.1 20210110]
smart_open 5.2.1
paramiko 2.7.2
```

#### Checklist

Before you create the issue, please make sure you have:

- [x] Described the problem clearly
- [x] Provided a minimal reproducible example, including any required data
- [x] Provided the version numbers of the relevant software

**Comment by mpenkov** [comment]
Thank you for reporting this. Are you interested in making a PR?

**Comment by qlessdev** [comment]
Sure, I can work on PR, although not familiar with the process, so instructions would be helpful, also I'll be using @dotdev01 user account for it.
