### ISSUE TITLE
S3 Multipart uploads comitted on exception when using compression via context manager

### ISSUE THREAD

**Issue by Limess** [piskvorky/smart_open#684]
#### Problem description

- We're trying to upload gzipped objects to S3, using multipart upload
- We're using a context manager to open a gzipped output file in S3, and writing to the file. When the writing throws an exception we expect the multipart upload to be terminated
- The multipart upload is commited

This is because when using a context manager around a compressed file, the `MultipartWriter` `__exit__` method will not be called on https://github.com/RaRe-Technologies/smart_open/blob/59d3a6079b523c030c78a3935622cf94405ce052/smart_open/s3.py#L938-L942

We've seen two resulting behaviours from this issue:

1. Empty or incomplete multipart uploads are written, this seems to be as expected when `__exit__` is not called correctly
2. Corrupted gzipped files being written. We're less sure how this occured

#### Steps/code to reproduce the problem

```python
import smart_open

with smart_open.open(
    s3.s3_uri(output_bucket, "test-file.gz"),
    "wb",
) as fout:
    for data in ["valid-data", Exception("An exception")]:
		if isinstance(data, Exception)
			raise data
    	fout.write((doc + "\n").encode("utf-8"))
```

#### Versions

```python
>>> import platform, sys, smart_open
m.platform())
print("Python", sys.version)
print("smart_open", smart_open.__version__)>>> print(platform.platform())
Linux-5.10.60.1-microsoft-standard-WSL2-x86_64-with-debian-bullseye-sid
>>> print("Python", sys.version)
Python 3.7.11 (default, Jan 13 2022, 14:48:06)
[GCC 9.3.0]
>>> print("smart_open", smart_open.__version__)
smart_open 5.2.1
```

**Comment by mpenkov** [comment]
Thank you for reporting this. Are you interested in making a PR?

**Comment by Limess** [comment]
Not right now, sorry - I'm not that comfortable writing Python code.

**Comment by mpenkov** [comment]
No updates on this. Yes, please go ahead.

**Comment by lociko** [comment]
I think is not enough. We already have a tweak_close:
```python

def tweak_close(outer, inner):
    """Ensure that closing the `outer` stream closes the `inner` stream as well.

    Use this when your compression library's `close` method does not
    automatically close the underlying filestream.  See
    https://github.com/RaRe-Technologies/smart_open/issues/630 for an
    explanation why that is a problem for smart_open.
    """
    outer_close = outer.close

    def close_both(*args):
        nonlocal inner
        try:
            outer_close()
        finally:
            if inner:
                inner, fp = None, inner
                fp.close()

    outer.close = close_both
```

Which close underlying streams but in the case of S3 MultipartWriter we want to terminate (abort) uploading if an error is raised.
Like in this pice of code:
https://github.com/RaRe-Technologies/smart_open/blob/59d3a6079b523c030c78a3935622cf94405ce052/smart_open/s3.py#L938-L942

**Comment by lociko** [comment]
@mpenkov  I'm not sure how to determine when it is being called as part of exception handling or not so I decided to use `sys.exc_info()`.

**Comment by ddelange** [comment]
similar issue with Azure https://github.com/RaRe-Technologies/smart_open/pull/783

**Comment by ddelange** [comment]
> @mpenkov I'm not sure how to determine when it is being called as part of exception handling or not so I decided to use `sys.exc_info()`.

using `sys.exc_info()` will cause erroneous behaviour: if you want to write a log file to s3 during handling of some other upstream exception, you're inside an exception context (and you still want your multipart upload of the log file to succeed).
