### ISSUE TITLE
Consider using bz2file for python < 3 to support multistreams bz2

### ISSUE THREAD

**Issue by pombredanne** [piskvorky/smart_open#7]
Large bz2 files are often processed with pbzip2 and end up being multistream files. Python 2.7 does not handle them yet (Py 3 does). bz2file is a backport of that (by the author of the feature) to py 2.7
https://github.com/nvawda/bz2file
https://pypi.python.org/pypi/bz2file/0.98
I got bitten by that, so I wanted to share it...
/HTH

**Comment by pombredanne** [comment]
oh and BTW, Py 2.7 silently ignore the multiple streams... So unless you are careful you may end by extracting only part of a file, without knowing it.

**Comment by piskvorky** [comment]
I didn't know, thanks!

We intend to support py2.6 too, would that work there as well?

**Comment by piskvorky** [comment]
Never mind, docs say it supports >=2.6 :+1: 

Can you do a pull request for this "multistream bz2"?

**Comment by pombredanne** [comment]
@piskvorky sure, let craft a quick commit later today

**Comment by pombredanne** [comment]
here is the fix.
