### ISSUE TITLE
Update license trove classifier to reflect MIT license

### ISSUE THREAD

**Issue by gwachob** [piskvorky/smart_open#72]
Hi-

In LICENSE you have a MIT license, but in the trove classifier for licenses, you have "Public Domain". In fact, those are separate licensing regimes. 
    
Instead of `License :: Public Domain` in your setup.py you probably want `License :: OSI Approved :: MIT License`, so the metadata in/from PyPI is correct.

**Comment by tmylk** [comment]
Fixed in https://github.com/piskvorky/smart_open/commit/62d58123a6fca0a5387d2454474407fded2d21bf Thanks for catching this!
