### ISSUE TITLE
pip install for version 3.0.0 failig

### ISSUE THREAD

**Issue by gerardorosiles** [piskvorky/smart_open#794]
I am standing up an old application 

When running:
pip install smart_open==3.0.0

or

pip install smart_open==4.0.0

The following error is reported:
`  
Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in smart_open setup command: 'python_requires' must be a string containing valid version specifiers; Invalid specifier: '>=3.5.*'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
`

**Comment by CloudNiner** [comment]
You're likely running into https://github.com/piskvorky/smart_open/pull/639

In order to fix this our org had to fork this repo, push the same fix to a new branch there and then install from our fork instead, for smart_open versions <5.1.0.

@piskvorky is there any chance this fix could be backported to the 4.0 release series as a 4.2.1 release?

**Comment by piskvorky** [comment]
Why would you install smart-open 3.x or 4.x, rather than the latest? What's the motivation here?

**Comment by CloudNiner** [comment]
I can't speak for @gerardorosiles but for our case smart open is being pulled transitively by another dependency in our project that locks to smart_open<5. It would be significant effort for us to update that parent dependency, which is lower priority than lots of other things on our roadmap, hence the workaround described above.

**Comment by cfloressuazo** [comment]
Same here, it happens with `pip install smart_open==4.0.1`

**Comment by ddelange** [comment]
fixed as of v5.2.0 ref https://github.com/piskvorky/smart_open/commit/0f8990266da3e0343b3b03bd7007a2d0b77843f5

**Comment by gerardorosiles** [comment]
@piskvorky  This is legacy code that we are tasked with deploying. As per the documentation I am reading, moving to > 5.0.0 introduces breaking changes, and we are not authorized  (e.g., under contract) to refactor the code.

As a test I did try updating to version 5.2.0 (we can tweak the requirements.txt file) and as mentioned by @CloudNiner other dependencies are also locked into version  3.0.0. So this issue creates a domino effec.

**Comment by piskvorky** [comment]
@gerardorosiles what's the import chain = which library pins smart_open to an older version?

**Comment by ddelange** [comment]
you can always make a public fork of smart_open, branch off a specific version, manually change that line in setup.py, and add to your requirements.txt `smart_open @ https://github.com/<owner>/smart_open/archive/refs/heads/<branch>.zip` (and should be compatible with the other legacy projects pinning v3).

**Comment by mpenkov** [comment]
The workaround described by @CloudNiner and @ddelange sounds like it would work, although it is a bit ugly.

The alternatives are:

- Update dependencies so that more recent smart_open versions are used (as suggested by @piskvorky): burden for @CloudNiner and @gerardorosiles, other priorities
- Backport the fix, release smart_open 3.0.1 and 4.0.1 (effort for @mpenkov, we've never done this before, uncharted territory, other priorities)

**Comment by mpenkov** [comment]
Have you guys tried downgrading your pip just to install smart_open 3.0 or 4.0?

version 3.0 and 4.0 pip-installed successfully back in the day, so this strict python_requires check must be a relatively recently added thing.

**Comment by ddelange** [comment]
> Have you guys tried downgrading your pip just to install smart_open 3.0 or 4.0?

good idea @mpenkov!

I can confirm it's not pip but rather setuptools 67.0.0 which introduced this check:

```console
$ pip install -U pip setuptools==66.1.1 wheel
...
$ pip install smart_open==3.0.0
Collecting smart_open==3.0.0
  Downloading smart_open-3.0.0.tar.gz (113 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 113.0/113.0 kB 773.2 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... done 🎉
...
Successfully installed smart_open-3.0.0
```

**Comment by gerardorosiles** [comment]
Thanks for your attention and suggestions.

@mpenkov  I tried downgrading pip as suggested and did not work. I found the smart-open issue also discussed in setuptools project here:
[https://github.com/pypa/setuptools/issues/1049]

@ddelange Thanks very much for the solution. So this issue will happen for setuptools >=67 (I was using 68.0.0)

@piskvorky When updating to smart-open 5.0.0 I got this error for the pathy library.

`ERROR: Cannot install -r requirements.txt (line 51) and smart-open==5.0.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested smart-open==5.0.0
    pathy 0.4.0 depends on smart-open<4.0.0 and >=2.2.0
`

Thanks again for all your help.

**Comment by piskvorky** [comment]
Current pathy requires `smart-open>=5.2.1,<7.0.0`: https://github.com/justindujardin/pathy/blob/master/requirements.txt https://github.com/justindujardin/pathy/blob/master/requirements.txt

Which is fine. So this moves the real problem higher up your dependency chain – it's not smart_open, and it's not pathy.

I'd suggest contacting the maintainer of the ultimate culprit to upgrade their dependencies. Unless it's you, "under contract not to upgrade", in which case you're out of luck I suppose.
