### ISSUE TITLE
The result of smart_open.open (FileLikeProxy) lacks a __next__-method in 7.0.0 whereas in 6.4.0 (_io.TextIOWrapper) it did

### ISSUE THREAD

**Issue by PatrikBernhard** [piskvorky/smart_open#810]
#### Problem description

In smart_open 6.4.0 smart_open.open returns an iterable (_io.TextIOWrapper) which has a __next__-method for s3files; in 7.* this does not seem to be the case anymore.

e.g. smart_open.open(uri="s3://test/output.csv") returns a FileLikeProxy which is an iterable without __next__.

- What is the expected result?
That when next() is called on the object returned by smart_open.open, an error is not thrown but the next item in the iterator is returned.

- What are you seeing instead?
TypeError: 'FileLikeProxy' object is not an iterator

#### Steps/code to reproduce the problem

import moto
import boto3
import smart_open
print(f"{boto3.__version__=}")  # boto3.__version__='1.33.13'
print(f"{smart_open.__version__=}")  # smart_open.__version__='7.0.1'

with moto.mock_aws():
    s3 = boto3.client("s3")
    s3.create_bucket(Bucket="test")
    s3.put_object(Bucket="test", Key="output.csv",  Body="abc\ndef\nghi")
    f = smart_open.open(uri="s3://test/output.csv")

print(next(f))  # "'abc\n'" in smart_open.__version__ = '6.4.0'

#### Versions

macOS-10.16-x86_64-i386-64bit
Python 3.11.7 (main, Dec 15 2023, 12:09:04) [Clang 14.0.6 ]
smart_open 7.0.1

#### Checklist

Before you create the issue, please make sure you have:

- [X] Described the problem clearly
- [X] Provided a minimal reproducible example, including any required data
- [X] Provided the version numbers of the relevant software

**Comment by mpenkov** [comment]
Sounds like it may be relevant to https://github.com/piskvorky/smart_open/pull/786

@ddelange Can you please have a look?

**Comment by ddelange** [comment]
tnx for the ping, will have a look tomorrow

**Comment by ddelange** [comment]
PR is up ^ no idea why wrapt is not proxying `__next__` by default
[![https://http.cat/417](https://http.cat/417)](https://http.cat/417)

**Comment by PatrikBernhard** [comment]
Thanks, excellent response time. Great job!

**Comment by mpenkov** [comment]
I'll do a bugfix release today
