### ISSUE TITLE
FTP stream decompression - unable to transparently decompress

### ISSUE THREAD

**Issue by nickmtrendii** [piskvorky/smart_open#841]
#### Problem description

Be sure your description clearly answers the following questions:

When attempting to decompress a file stream from an FTP source, I am getting
```
WARNING unable to transparently decompress <_io.BufferedReader name=4> because it seems to lack a string-like .name
```
This then causes errors as it returns the still compressed file blob.

#### Steps/code to reproduce the problem

```python
import smart_open
import logging
logging.basicConfig(
    level='DEBUG'
)

def main():
    streamreader = smart_open.open(uri='ftp://myftp.example//myfile.txt.gz', mode='r', errors='surrogateescape', encoding='utf-8')
    print(streamreader.__next__())

if __name__ == '__main__':
    main()
```

Output:
```
DEBUG:smart_open.smart_open_lib:{'uri': 'ftp://myftp.example//myfile.txt.gz', 'mode': 'r', 'buffering': -1, 'encoding': 'utf-8', 'errors': 'surrogateescape', 'newline': None, 'closefd': True, 'opener': None, 'compression': 'infer_from_extension', 'transport_params': None}
WARNING:smart_open.compression:unable to transparently decompress <_io.BufferedReader name=580> because it seems to lack a string-like .name
DEBUG:smart_open.smart_open_lib:encoding_wrapper: {'fileobj': <_io.BufferedReader name=580>, 'mode': 'r', 'encoding': 'utf-8', 'errors': 'surrogateescape', 'newline': None}
▼���r�8��y�O����ٰ\♦�����Gf�TWugMWTfw�\9(        �X�H5I��        ]���l►�-�i��G��g.&�2y�u@�~▬A|���ok?�A��ُe���9�%-n�bz�R6�n�:+♂V��☼⌂a�Vj��▬�}�▬���}��a������D�������<��t��♂�ؗ"�↨��Oy�`?��J������O�����fu�>�dEqϲ�������
```

I (poorly) tweaked [smart_open_lib.py#L225](https://github.com/piskvorky/smart_open/blob/develop/smart_open/smart_open_lib.py#L225) to include the `filename` param and it works to decode my file.

```python
    decompressed = so_compression.compression_wrapper(binary, binary_mode, compression, filename=os.path.basename(uri))
```

#### Versions
```
Windows-10-10.0.19045-SP0
Python 3.13.0 (tags/v3.13.0:60403a5, Oct  7 2024, 09:38:07) [MSC v.1941 64 bit (AMD64)]
smart_open 7.0.5
```

#### Checklist

Before you create the issue, please make sure you have:

- [X] Described the problem clearly
- [X] Provided a minimal reproducible example, including any required data
- [X] Provided the version numbers of the relevant software

**Comment by ddelange** [comment]
no need for the `basename` call, passing `filename=uri` should be sufficient and OK since it's always available there anyway. @mpenkov any reason _not_ to add this?

**Comment by mpenkov** [comment]
No, can't think of one.

**Comment by ddelange** [comment]
thanks for the bug report @nickmtrendii 👍
