### ISSUE TITLE
Test failure with Python 3.13

### ISSUE THREAD

**Issue by tillea** [piskvorky/smart_open#846]
#### Problem description

The Debian package received a [bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1089053) about a failure of the test suite.

#### Steps/code to reproduce the problem

I reproduced the issue in the [CI of the Debian development platform](https://salsa.debian.org/python-team/packages/smart-open/-/jobs/6755885#L3965) which reproduces the issue:

    ____________________ WriterTest.test_nonexisting_container _____________________
    self = <[AttributeError("'Writer' object has no attribute '_blob'") raised in repr()] Writer object at 0x7f46b7e3fa90>
        def __repr__(self):
            return "%s(container=%r, blob=%r, min_part_size=%r)" % (
                self.__class__.__name__,
                self._container_name,
    >           self._blob.blob_name,
                self._min_part_size
            )
    E       AttributeError: 'Writer' object has no attribute '_blob'
    smart_open/azure.py:538: AttributeError

The CI contains the [full build log](https://salsa.debian.org/python-team/packages/smart-open/-/jobs/6755885#L3965) to inform you about all involved versions.

#### Versions

Please provide the output of:

    platform linux -- Python 3.13.1, pytest-8.3.4, pluggy-1.5.0

The former package smart_open 7.0.5-1 was building fine using Python 3.12

Kind regards, Andreas.

**Comment by ddelange** [comment]
Interesting for two reasons:
- [the test](https://github.com/piskvorky/smart_open/blob/v7.0.5/smart_open/tests/test_azure.py#L825) should fail on hitting [this call](https://github.com/piskvorky/smart_open/blob/v7.0.5/smart_open/tests/test_azure.py#L130), but apparently it doesn't, or it does and py313 tries to do a repr for the traceback before pytest can catch it?
- [the Writer](https://github.com/piskvorky/smart_open/blob/v7.0.5/smart_open/azure.py#L398) _always_ has `_blob` populated, so I see no reason for repr to fail

**Comment by ddelange** [comment]
this really is a python 3.13 thing: https://github.com/piskvorky/smart_open/pull/847#issuecomment-2544133399

pytest only calls repr to build the traceback.

**Comment by ddelange** [comment]
@tillea smart_open 7.1.0 has been released
